"""
Dicionário de palavras-chave e padrões linguísticos para classificação emocional.

Organizado por nível de risco:
  - ALTO: sinais de desesperança, risco à vida
  - MODERADO: sobrecarga emocional, sofrimento repetido
  - LEVE: desconforto emocional leve

Inclui também categorias corporativas (burnout, ansiedade, depressão,
estresse laboral, clima organizacional) para conformidade NR-01.
"""


KEYWORDS_ALTO = [
    "não quero mais viver",
    "nao quero mais viver",
    "queria sumir",
    "quero sumir",
    "não vejo saída",
    "nao vejo saida",
    "não vejo saida",
    "desistir de tudo",
    "acabar com tudo",
    "quero morrer",
    "queria morrer",
    "me matar",
    "vontade de morrer",
    "não vale a pena",
    "nao vale a pena",
    "sem razão pra viver",
    "sem razao pra viver",
    "cansado de viver",
    "cansada de viver",
    "não aguento mais viver",
    "nao aguento mais viver",
    "quero desaparecer",
    "queria desaparecer",
    "ninguém se importa",
    "ninguem se importa",
    "seria melhor sem mim",
    "melhor sem mim",
    "não faz sentido continuar",
    "nao faz sentido continuar",
    "pensando em acabar",
    "quero dar um fim",
    "dar um fim em tudo",
    "não tenho motivo pra viver",
    "nao tenho motivo pra viver",
    "vida não tem sentido",
    "vida nao tem sentido",
    "perdi a vontade de viver",
    "sem vontade de viver",
    "quero ir embora pra sempre",
]

KEYWORDS_MODERADO = [
    "não aguento mais",
    "nao aguento mais",
    "tô muito mal",
    "to muito mal",
    "estou muito mal",
    "ansioso",
    "ansiosa",
    "ansiedade",
    "esgotado",
    "esgotada",
    "esgotamento",
    "sobrecarregado",
    "sobrecarregada",
    "sobrecarga",
    "sufocado",
    "sufocada",
    "não consigo mais",
    "nao consigo mais",
    "muito mal",
    "muito triste",
    "muito cansado",
    "muito cansada",
    "tô péssimo",
    "to pessimo",
    "estou péssimo",
    "estou péssima",
    "desespero",
    "desesperado",
    "desesperada",
    "angústia",
    "angustia",
    "angustiado",
    "angustiada",
    "não sei o que fazer",
    "nao sei o que fazer",
    "me sinto preso",
    "me sinto presa",
    "tudo dando errado",
    "nada dá certo",
    "nada da certo",
    "chorando muito",
    "não paro de chorar",
    "nao paro de chorar",
    "crises de choro",
    "pressão demais",
    "pressao demais",
    "não durmo",
    "nao durmo",
    "insônia",
    "insonia",
    "não consigo dormir",
    "nao consigo dormir",
    "pânico",
    "panico",
    "crise de pânico",
    "crise de panico",
    "burnout",
    "perdendo o controle",
    "descontrolado",
    "descontrolada",
]

KEYWORDS_LEVE = [
    "cansado",
    "cansada",
    "desanimado",
    "desanimada",
    "sem energia",
    "meio triste",
    "um pouco triste",
    "entediado",
    "entediada",
    "desmotivado",
    "desmotivada",
    "chateado",
    "chateada",
    "irritado",
    "irritada",
    "estressado",
    "estressada",
    "desconfortável",
    "desconfortavel",
    "insatisfeito",
    "insatisfeita",
    "frustrado",
    "frustrada",
    "incomodado",
    "incomodada",
    "preocupado",
    "preocupada",
    "solitário",
    "solitaria",
    "sozinho",
    "sozinha",
    "triste",
    "mal",
    "ruim",
    "péssimo",
    "pessimo",
    "pra baixo",
    "cabisbaixo",
    "cabisbaixa",
    "melancólico",
    "melancolico",
    "melancólica",
    "melancolica",
    "sem ânimo",
    "sem animo",
    "sem vontade",
    "deslocado",
    "deslocada",
]


PALAVRAS_ABSOLUTAS = [
    "nada",
    "tudo",
    "nunca",
    "sempre",
    "ninguém",
    "ninguem",
    "nenhum",
    "nenhuma",
    "jamais",
    "impossível",
    "impossivel",
    "completamente",
    "totalmente",
]

PADROES_NEGATIVOS = [
    "não consigo",
    "nao consigo",
    "não sei",
    "nao sei",
    "não tenho",
    "nao tenho",
    "não posso",
    "nao posso",
    "não quero",
    "nao quero",
    "cansei de",
    "cansado de",
    "cansada de",
    "farto de",
    "farta de",
    "odeio",
    "detesto",
]

AUSENCIA_ESPERANCA = [
    "sem esperança",
    "sem esperanca",
    "sem saída",
    "sem saida",
    "sem futuro",
    "sem sentido",
    "sem propósito",
    "sem proposito",
    "sem motivo",
    "sem razão",
    "sem razao",
    "perdido",
    "perdida",
    "vazio",
    "vazia",
    "oco",
    "oca",
]


CATEGORIAS_CORPORATIVAS = {
    "burnout": [
        "burnout",
        "esgotado",
        "esgotada",
        "esgotamento",
        "exausto",
        "exhausta",
        "exaustão",
        "exaustao",
        "sem energia pra trabalhar",
        "não aguento mais trabalhar",
        "nao aguento mais trabalhar",
        "sobrecarregado no trabalho",
        "sobrecarregada no trabalho",
        "trabalho demais",
        "horas extras demais",
        "não tenho tempo pra nada",
        "nao tenho tempo pra nada",
        "vivendo pra trabalhar",
        "trabalho sem parar",
        "não consigo descansar",
        "nao consigo descansar",
        "levo trabalho pra casa",
        "penso no trabalho o tempo todo",
        "fim de semana trabalhando",
        "não tiro férias",
        "nao tiro ferias",
        "acumulando função",
        "acumulando funcao",
        "cansado de trabalhar",
        "cansada de trabalhar",
    ],
    "ansiedade": [
        "ansioso",
        "ansiosa",
        "ansiedade",
        "pânico",
        "panico",
        "crise de ansiedade",
        "crise de pânico",
        "crise de panico",
        "nervoso",
        "nervosa",
        "apreensivo",
        "apreensiva",
        "medo de errar",
        "medo de ser demitido",
        "medo de ser demitida",
        "inseguro",
        "insegura",
        "insegurança",
        "inseguranca",
        "coração acelerado",
        "coracao acelerado",
        "tremendo",
        "suando frio",
        "não consigo me concentrar",
        "nao consigo me concentrar",
        "pensamento acelerado",
        "preocupado demais",
        "preocupada demais",
    ],
    "depressão": [
        "deprimido",
        "deprimida",
        "depressão",
        "depressao",
        "sem vontade de nada",
        "não sinto prazer",
        "nao sinto prazer",
        "não tenho motivação",
        "nao tenho motivacao",
        "perdi o interesse",
        "nada me anima",
        "me sinto vazio",
        "me sinto vazia",
        "choro sem motivo",
        "tristeza profunda",
        "sem esperança",
        "sem esperanca",
        "isolado",
        "isolada",
        "me afastando de todos",
        "não quero sair de casa",
        "nao quero sair de casa",
        "sem energia pra nada",
    ],
    "estresse_laboral": [
        "estressado",
        "estressada",
        "estresse",
        "pressão do chefe",
        "pressao do chefe",
        "pressão no trabalho",
        "pressao no trabalho",
        "metas impossíveis",
        "metas impossiveis",
        "meta absurda",
        "cobrança demais",
        "cobranca demais",
        "muita cobrança",
        "muita cobranca",
        "prazos apertados",
        "prazo impossível",
        "prazo impossivel",
        "demanda alta",
        "muita demanda",
        "sobrecarga de trabalho",
        "não dou conta",
        "nao dou conta",
        "trabalho tóxico",
        "trabalho toxico",
        "ambiente tóxico",
        "ambiente toxico",
        "pressão por resultado",
        "pressao por resultado",
    ],
    "clima_organizacional": [
        "assédio",
        "assedio",
        "assédio moral",
        "assedio moral",
        "humilhação",
        "humilhacao",
        "humilhado",
        "humilhada",
        "desrespeitado",
        "desrespeitada",
        "não sou ouvido",
        "nao sou ouvido",
        "não sou ouvida",
        "nao sou ouvida",
        "não me valorizam",
        "nao me valorizam",
        "não reconhecido",
        "nao reconhecido",
        "não reconhecida",
        "nao reconhecida",
        "chefe tóxico",
        "chefe toxico",
        "liderança ruim",
        "lideranca ruim",
        "clima pesado",
        "fofoca no trabalho",
        "competição tóxica",
        "competicao toxica",
        "excluído",
        "excluida",
        "discriminação",
        "discriminacao",
        "favoritismo",
        "injustiça",
        "injustica",
        "relação ruim com chefe",
        "relacao ruim com chefe",
    ],
}
